import dotenv from "dotenv";
dotenv.config();
import mongoose from "mongoose";
import { DB_NAME } from "../constants.js";
import { Food } from "../models/food.model.js";

const SEED_FOODS = [
  // ==================== BREAKFAST (8 Items) ====================
  {
    itemname: "masala dosa",
    category: "BreakFast",
    price: 60,
    originalPrice: 70,
    offer: 14,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Crispy golden fermented crepe stuffed with spiced potato masala, served with coconut chutney & piping hot sambar.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 34,
  },
  {
    itemname: "idli vada sambar combo",
    category: "BreakFast",
    price: 45,
    originalPrice: 50,
    offer: 10,
    isVeg: true,
    inStock: true,
    stock: 60,
    description: "Steamed fluffy rice cakes paired with crispy medu vada, served with traditional lentil sambar and fresh coconut chutney.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 42,
  },
  {
    itemname: "puri bhaji",
    category: "BreakFast",
    price: 50,
    originalPrice: 55,
    offer: 9,
    isVeg: true,
    inStock: true,
    stock: 45,
    description: "Three fluffy golden puffed wheat puris served with authentic spiced potato curry and zesty mixed pickle.",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 28,
  },
  {
    itemname: "poha with sev",
    category: "BreakFast",
    price: 35,
    originalPrice: 40,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Flattened rice tempered with mustard seeds, crunchy roasted peanuts, turmeric, onions, and topped with crispy sev.",
    image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.5,
    totalRatings: 23,
  },
  {
    itemname: "rava upma",
    category: "BreakFast",
    price: 35,
    originalPrice: 40,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 40,
    description: "Semolina porridge tempered with curry leaves, cashews, ginger, and green chilies, served with coconut chutney.",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.4,
    totalRatings: 18,
  },
  {
    itemname: "paneer paratha",
    category: "BreakFast",
    price: 65,
    originalPrice: 75,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Whole wheat flatbread stuffed with spiced grated cottage cheese, served with fresh curd and mixed pickle.",
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 37,
  },
  {
    itemname: "aloo paratha with butter",
    category: "BreakFast",
    price: 55,
    originalPrice: 65,
    offer: 15,
    isVeg: true,
    inStock: true,
    stock: 55,
    description: "Homestyle griddle flatbread filled with spiced mashed potatoes, topped with a generous dollop of white butter.",
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 31,
  },
  {
    itemname: "chole bhature",
    category: "BreakFast",
    price: 75,
    originalPrice: 85,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Two giant deep-fried sourdough bhatures served with rich, aromatic Punjabi chickpea masala and pickled onions.",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 49,
  },

  // ==================== LUNCH (8 Items) ====================
  {
    itemname: "north indian special thali",
    category: "Lunch",
    price: 120,
    originalPrice: 140,
    offer: 14,
    isVeg: true,
    inStock: true,
    stock: 60,
    description: "Complete meal with 2 butter rotis, steamed basmati rice, paneer sabzi, dal tadka, salad, papad & sweet gulab jamun.",
    image: "https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 54,
  },
  {
    itemname: "south indian meals",
    category: "Lunch",
    price: 90,
    originalPrice: 100,
    offer: 10,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Traditional boiled rice served with sambar, rasam, kootu, poriyal, appalam, curd, and seasonal mango pickle.",
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 29,
  },
  {
    itemname: "chicken dum biryani",
    category: "Lunch",
    price: 160,
    originalPrice: 180,
    offer: 11,
    isVeg: false,
    inStock: true,
    stock: 50,
    description: "Slow-cooked fragrant long-grain basmati rice layered with tender marinated chicken pieces, served with mirchi salan & raita.",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 68,
  },
  {
    itemname: "hyderabadi veg biryani",
    category: "Lunch",
    price: 120,
    originalPrice: 135,
    offer: 11,
    isVeg: true,
    inStock: true,
    stock: 45,
    description: "Aromatic basmati rice cooked on dum with garden-fresh vegetables, paneer cubes, saffron, fried onions, and whole spices.",
    image: "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 38,
  },
  {
    itemname: "paneer butter masala combo",
    category: "Lunch",
    price: 130,
    originalPrice: 150,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Rich velvety tomato-cashew gravy with soft paneer cubes, served with 2 butter naans and steamed jeera rice.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 44,
  },
  {
    itemname: "dal makhani with jeera rice",
    category: "Lunch",
    price: 100,
    originalPrice: 115,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Creamy slow-cooked black lentils simmered overnight with butter and fresh cream, paired with fragrant jeera rice.",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 33,
  },
  {
    itemname: "rajma chawal bowl",
    category: "Lunch",
    price: 85,
    originalPrice: 95,
    offer: 10,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Comforting Kashmiri red kidney beans cooked in homestyle onion-tomato gravy, served over hot steamed basmati rice.",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 27,
  },
  {
    itemname: "egg fried rice with manchurian",
    category: "Lunch",
    price: 110,
    originalPrice: 125,
    offer: 12,
    isVeg: false,
    inStock: true,
    stock: 45,
    description: "Wok-tossed aromatic rice with scrambled eggs, crunchy scallions, accompanied by savory vegetable manchurian gravy.",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 36,
  },

  // ==================== PIZZA (8 Items) ====================
  {
    itemname: "margherita cheese pizza",
    category: "Pizza",
    price: 130,
    originalPrice: 150,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Classic Italian 8-inch hand-stretched crust topped with rich tomato sauce, melted mozzarella, and fragrant fresh basil.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 41,
  },
  {
    itemname: "farmhouse fresh veggie pizza",
    category: "Pizza",
    price: 170,
    originalPrice: 195,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Loaded with crispy bell peppers, red onions, ripe tomatoes, sliced button mushrooms, and gooey mozzarella cheese.",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 39,
  },
  {
    itemname: "peppy paneer pizza",
    category: "Pizza",
    price: 190,
    originalPrice: 220,
    offer: 14,
    isVeg: true,
    inStock: true,
    stock: 45,
    description: "Chunky marinated paneer cubes, spicy red paprika, crisp capsicum, and melted cheddar-mozzarella blend.",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 48,
  },
  {
    itemname: "cheesy corn & mushroom pizza",
    category: "Pizza",
    price: 160,
    originalPrice: 180,
    offer: 11,
    isVeg: true,
    inStock: true,
    stock: 40,
    description: "Sweet golden American corn kernels and sauteed button mushrooms on a creamy garlic-infused cheese base.",
    image: "https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 25,
  },
  {
    itemname: "barbecue chicken pizza",
    category: "Pizza",
    price: 210,
    originalPrice: 240,
    offer: 12,
    isVeg: false,
    inStock: true,
    stock: 45,
    description: "Smoked tender chicken chunks smothered in sweet-tangy hickory BBQ sauce with red onions and melted mozzarella.",
    image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 52,
  },
  {
    itemname: "spicy chicken sausage pizza",
    category: "Pizza",
    price: 200,
    originalPrice: 230,
    offer: 13,
    isVeg: false,
    inStock: true,
    stock: 40,
    description: "Juicy sliced chicken sausages, jalapeño slices, hot chili flakes, and double layers of melted cheese.",
    image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 34,
  },
  {
    itemname: "double cheese burst margherita",
    category: "Pizza",
    price: 160,
    originalPrice: 185,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 45,
    description: "Crust oozing with warm liquid cheese sauce inside, crowned with herb-seasoned shredded mozzarella on top.",
    image: "https://images.unsplash.com/photo-1594007654729-407edc4be65b?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 40,
  },
  {
    itemname: "paneer tikka makhani pizza",
    category: "Pizza",
    price: 195,
    originalPrice: 225,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 40,
    description: "Desi fusion pizza with makhani gravy sauce, tandoori paneer tikka, sliced red onions, and fresh coriander.",
    image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 37,
  },

  // ==================== BURGERS (8 Items) ====================
  {
    itemname: "classic veg burger",
    category: "Burgers",
    price: 70,
    originalPrice: 80,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Crispy seasoned vegetable patty, fresh lettuce, juicy tomato slices, and tangy mayo between toasted sesame buns.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 45,
  },
  {
    itemname: "crispy chicken burger",
    category: "Burgers",
    price: 110,
    originalPrice: 125,
    offer: 12,
    isVeg: false,
    inStock: true,
    stock: 50,
    description: "Golden fried crunchy chicken breast fillet topped with creamy coleslaw, dill pickles, and spicy chipotle sauce.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 61,
  },
  {
    itemname: "spicy paneer burger",
    category: "Burgers",
    price: 95,
    originalPrice: 110,
    offer: 14,
    isVeg: true,
    inStock: true,
    stock: 45,
    description: "Crispy coated tandoori paneer slab, crunchy iceberg lettuce, and spicy mint mayo on a toasted brioche bun.",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 39,
  },
  {
    itemname: "double cheese burger",
    category: "Burgers",
    price: 120,
    originalPrice: 140,
    offer: 14,
    isVeg: true,
    inStock: true,
    stock: 45,
    description: "Double crispy patties stacked with two melted cheddar cheese slices, caramelized onions, and secret burger spread.",
    image: "https://images.unsplash.com/photo-1583032015879-66c5faee0fa4?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 43,
  },
  {
    itemname: "aloo tikki burger",
    category: "Burgers",
    price: 55,
    originalPrice: 65,
    offer: 15,
    isVeg: true,
    inStock: true,
    stock: 60,
    description: "Spiced crispy potato & green pea patty, crunchy onion rings, sliced tomatoes, and tangy imli sauce in soft bun.",
    image: "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 50,
  },
  {
    itemname: "bbq chicken burger",
    category: "Burgers",
    price: 130,
    originalPrice: 150,
    offer: 13,
    isVeg: false,
    inStock: true,
    stock: 40,
    description: "Smoky grilled chicken patty glazed in barbecue sauce, melted cheese slice, and grilled caramelized red onions.",
    image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 35,
  },
  {
    itemname: "mushroom swiss burger",
    category: "Burgers",
    price: 115,
    originalPrice: 130,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 35,
    description: "Hearty sautéed garlic mushrooms, melted Swiss cheese, fresh crisp lettuce, and truffle mayo on toasted bun.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 26,
  },
  {
    itemname: "peri peri veg burger",
    category: "Burgers",
    price: 85,
    originalPrice: 95,
    offer: 11,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Crunchy spicy vegetable patty dusted with zesty African bird's eye peri-peri seasoning and jalapeño mayo.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 31,
  },

  // ==================== BURGER (8 Items) ====================
  {
    itemname: "crispy zinger burger",
    category: "Burger",
    price: 125,
    originalPrice: 145,
    offer: 14,
    isVeg: false,
    inStock: true,
    stock: 50,
    description: "Extra crunchy hand-breaded chicken fillet with fiery red marinade, fresh shredded lettuce, and classic mayonnaise.",
    image: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 58,
  },
  {
    itemname: "jumbo maharaja burger",
    category: "Burger",
    price: 145,
    originalPrice: 170,
    offer: 15,
    isVeg: true,
    inStock: true,
    stock: 40,
    description: "Tall double-decker burger with two seasoned corn-cheese patties, crunchy salad, and rich cocktail sauce.",
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 44,
  },
  {
    itemname: "veggie deluxe burger",
    category: "Burger",
    price: 80,
    originalPrice: 90,
    offer: 11,
    isVeg: true,
    inStock: true,
    stock: 55,
    description: "Wholesome vegetable & lentil patty infused with herbs, sliced cucumbers, tomatoes, and garlic aioli.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 29,
  },
  {
    itemname: "tandoori chicken burger",
    category: "Burger",
    price: 135,
    originalPrice: 155,
    offer: 13,
    isVeg: false,
    inStock: true,
    stock: 45,
    description: "Char-grilled tandoori chicken thigh fillet marinated in spiced yogurt, mint coriander chutney, and pickled onions.",
    image: "https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 47,
  },
  {
    itemname: "corn & spinach burger",
    category: "Burger",
    price: 75,
    originalPrice: 85,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 45,
    description: "Golden fried patty of sweet corn and baby spinach blended with mild cheddar cheese, served with herb mayo.",
    image: "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 22,
  },
  {
    itemname: "grilled chicken burger",
    category: "Burger",
    price: 115,
    originalPrice: 130,
    offer: 12,
    isVeg: false,
    inStock: true,
    stock: 50,
    description: "Herb-marinated tender grilled chicken breast, sliced red ripe tomatoes, butter lettuce, and light honey mustard.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 36,
  },
  {
    itemname: "spicy mexican burger",
    category: "Burger",
    price: 90,
    originalPrice: 100,
    offer: 10,
    isVeg: true,
    inStock: true,
    stock: 40,
    description: "Bean and corn patty with pickled jalapeños, spicy salsa, guacamole spread, and crunchy nachos inside.",
    image: "https://images.unsplash.com/photo-1583032015879-66c5faee0fa4?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 28,
  },
  {
    itemname: "egg & cheese burger",
    category: "Burger",
    price: 65,
    originalPrice: 75,
    offer: 13,
    isVeg: false,
    inStock: true,
    stock: 50,
    description: "Sunny-side egg patty with melted American cheese, black pepper, sliced onions, and tomato ketchup in a toasted bun.",
    image: "https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 33,
  },

  // ==================== BEVERAGES (8 Items) ====================
  {
    itemname: "masala chai",
    category: "Beverages",
    price: 20,
    originalPrice: 25,
    offer: 20,
    isVeg: true,
    inStock: true,
    stock: 100,
    description: "Freshly brewed strong Assam tea leaves infused with crushed cardamom, ginger, cloves, and whole milk.",
    image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 85,
  },
  {
    itemname: "south indian filter coffee",
    category: "Beverages",
    price: 25,
    originalPrice: 30,
    offer: 17,
    isVeg: true,
    inStock: true,
    stock: 100,
    description: "Authentic decoction brewed in traditional brass filter with chicory blend, poured frothy in a stainless steel tumbler.",
    image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 76,
  },
  {
    itemname: "cold coffee with ice cream",
    category: "Beverages",
    price: 65,
    originalPrice: 75,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 60,
    description: "Thick chilled blended espresso milk drink topped with a generous scoop of vanilla ice cream and chocolate drizzle.",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 59,
  },
  {
    itemname: "mango lassi",
    category: "Beverages",
    price: 50,
    originalPrice: 60,
    offer: 17,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Creamy churned yogurt blended with sweet Alphonso mango pulp, fragrant cardamom, and garnished with chopped pistachios.",
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 48,
  },
  {
    itemname: "sweet lassi",
    category: "Beverages",
    price: 40,
    originalPrice: 45,
    offer: 11,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Traditional Punjabi thick yogurt drink churned with sugar, rose water essence, and a layer of fresh malai on top.",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 34,
  },
  {
    itemname: "hot chocolate",
    category: "Beverages",
    price: 60,
    originalPrice: 70,
    offer: 14,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Rich velvety melted dark chocolate drink whipped with steaming whole milk, dusted with premium Dutch cocoa powder.",
    image: "https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 42,
  },
  {
    itemname: "iced lemon tea",
    category: "Beverages",
    price: 45,
    originalPrice: 50,
    offer: 10,
    isVeg: true,
    inStock: true,
    stock: 60,
    description: "Crisp chilled Ceylon black tea shaken with fresh lemon juice, mint leaves, honey, and plenty of ice cubes.",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 36,
  },
  {
    itemname: "badam milk",
    category: "Beverages",
    price: 35,
    originalPrice: 40,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Warm sweetened milk infused with crushed roasted almonds, Kashmiri saffron strands, and fragrant green cardamom.",
    image: "https://images.unsplash.com/photo-1587080413959-06b859fb107d?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 27,
  },

  // ==================== DRINKS (8 Items) ====================
  {
    itemname: "fresh lime soda",
    category: "Drinks",
    price: 35,
    originalPrice: 40,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 80,
    description: "Fizzy effervescent soda prepared with freshly squeezed limes, rock salt, mint sprigs, and sweet-salt balance.",
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 56,
  },
  {
    itemname: "virgin mint mojito",
    category: "Drinks",
    price: 60,
    originalPrice: 70,
    offer: 14,
    isVeg: true,
    inStock: true,
    stock: 60,
    description: "Muddled fresh garden mint leaves, lime wedges, simple cane syrup, topped with sparkling club soda and crushed ice.",
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 63,
  },
  {
    itemname: "blue lagoon mocktail",
    category: "Drinks",
    price: 65,
    originalPrice: 75,
    offer: 13,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Vibrant electric blue curacao syrup shaken with tart lemon juice, Sprite, crushed ice, and garnished with a lemon wheel.",
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.8,
    totalRatings: 49,
  },
  {
    itemname: "fresh watermelon juice",
    category: "Drinks",
    price: 50,
    originalPrice: 60,
    offer: 17,
    isVeg: true,
    inStock: true,
    stock: 60,
    description: "Cold-pressed pure watermelon juice with a pinch of black salt and fresh mint, without any added artificial sugar.",
    image: "https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 41,
  },
  {
    itemname: "oreo thick milkshake",
    category: "Drinks",
    price: 75,
    originalPrice: 85,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Decadent creamy milkshake blended with crunchy Oreo cookies, vanilla ice cream, and finished with whipped cream.",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.9,
    totalRatings: 72,
  },
  {
    itemname: "strawberry milkshake",
    category: "Drinks",
    price: 70,
    originalPrice: 80,
    offer: 12,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Fresh strawberry puree whipped with rich chilled whole milk, strawberry ice cream, and drizzled with fruit compote.",
    image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 38,
  },
  {
    itemname: "green apple soda",
    category: "Drinks",
    price: 45,
    originalPrice: 50,
    offer: 10,
    isVeg: true,
    inStock: true,
    stock: 55,
    description: "Crisp tart green apple syrup topped with chilled sparkling club soda, lime zest, and cracked ice.",
    image: "https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.6,
    totalRatings: 24,
  },
  {
    itemname: "rose milk cooler",
    category: "Drinks",
    price: 40,
    originalPrice: 45,
    offer: 11,
    isVeg: true,
    inStock: true,
    stock: 50,
    description: "Classic nostalgic chilled milk drink infused with fragrant damask rose syrup and soaked sabja (basil) seeds.",
    image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=600&q=80",
    averageRating: 4.7,
    totalRatings: 30,
  },
];

async function runSeed() {
  const url = process.env.MONGODB_URL.includes("?")
    ? process.env.MONGODB_URL.replace("?", `${DB_NAME}?`)
    : `${process.env.MONGODB_URL}/${DB_NAME}`;

  console.log("Connecting to MongoDB at:", url);
  await mongoose.connect(url);

  console.log(`Checking and inserting ${SEED_FOODS.length} curated food items...`);

  let insertedCount = 0;
  let updatedCount = 0;

  for (const item of SEED_FOODS) {
    const cleanName = item.itemname.trim().toLowerCase();
    const existing = await Food.findOne({ itemname: cleanName });

    if (existing) {
      await Food.findByIdAndUpdate(existing._id, { $set: item });
      updatedCount++;
    } else {
      await Food.create(item);
      insertedCount++;
    }
  }

  console.log(`Seeding finished! Inserted: ${insertedCount}, Updated: ${updatedCount}`);

  // Summary per category
  const allFoodsInDb = await Food.find({});
  const countPerCat = {};
  allFoodsInDb.forEach((f) => {
    countPerCat[f.category] = (countPerCat[f.category] || 0) + 1;
  });

  console.log("Current Foods Count Per Category in DB:");
  console.table(countPerCat);

  await mongoose.disconnect();
}

runSeed().catch((err) => {
  console.error("Seeding failed with error:", err);
  process.exit(1);
});
